name: Build-Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Bump Version
        uses: opspresso/action-builder@v0.1.1
        with:
          args: --version

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm run build

      - name: Release
        uses: opspresso/action-builder@v0.1.1
        with:
          args: --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        uses: opspresso/action-docker@v0.1.1
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          LATEST: "true"
