name: Build-Push

on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

  version:
    needs: checkout
    runs-on: ubuntu-latest

      - name: Bump Version
        uses: opspresso/action-builder@v0.1.6
        with:
          args: --version

  build:
    needs: version
    runs-on: ubuntu-latest

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm run build

  release:
    needs: build
    runs-on: ubuntu-latest

      - name: Release to GitHub
        uses: opspresso/action-builder@v0.1.6
        with:
          args: --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ecr:
    needs: build
    runs-on: ubuntu-latest

      - name: Build & Push to AWS ECR
        uses: opspresso/action-builder@v0.1.6
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          LATEST: "true"

  docker:
    needs: build
    runs-on: ubuntu-latest

      - name: Build & Push to Docker Hub
        uses: opspresso/action-builder@v0.1.6
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          LATEST: "true"
